default:
  image: golang:1.17.0-alpine3.13

stages:
  - install
  - build
  - deploy

install-job:
  stage: install
  script:
    - go env -w GO111MODULE="on"
    - go env -w GOBIN=$GOPATH/bin
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - go install github.com/micro/micro/v2/cmd/protoc-gen-micro@latest
    - apk update
    - apk add --no-cache tzdata \
      && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  \
      && echo Asia/Shanghai > /etc/timezone \
      && apk del tzdata
      && apk add protoc
      && apk add make

build-job:
  stage: build
  only:
    - dev
    - master
  script:
    - make pbuild
    - cd vessel-service && make build && cd -
    - cd consignment-cli && make build && cd -
    - cd consignment-service && make build && cd -

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - cd consignment-service && make run && cd -
    - cd vessel-service && make run && cd -
    - cd consignment-cli && make run && cd -
